### ISSUE TITLE
Add suggestion for inclusive salutation 

### ISSUE THREAD

**Issue by sabderemane** [knyghty/bot#118]
Hi 👋🏽

I don't know how it's possible but I would like to have a (automatic ?) command to suggest a more inclusive salutation rather than "hey guys" with the link https://heyguys.cc/

**Comment by knyghty** [comment]
Sure, sounds good, PRs welcome.

It's certainly possible yeah, there's an example of responding to messages in this PR: https://github.com/knyghty/bot/pull/42

**Comment by nanorepublica** [comment]
Just a note that this has just been implemented via the MEE6 bot!

**Comment by knyghty** [comment]
Nice if I have to put less stuff in here
